Account/urls.py
from django.urls import path
from Account import views


app_name = 'account'
urlpatterns = [
    path('profile/', views.Profile.as_view(), name='profile'),
    path('profile/info', views.ProfileUpdate.as_view(), name='profile-update'),
    path('search/', views.search, name='search'),
    path('favorit/', views.FavoritMusic.as_view(), name='favorite'),
    path('playlist/', views.PlayListView.as_view(), name='playlist'),
    # Registration and Authentication :
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('register/', views.Register.as_view(), name='register'),
    path('active/<uidb64>/<token>/', views.activate, name='activate'),
    path('password_change/', views.change_password, name='password_change'),
    path('password_reset/', views.MyPasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.MyPasswordResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.MyPasswordResetConfirm.as_view(), name='password_reset_confirm'),
    # path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

Album/urls.py
from django.urls import path
from .views import AlbumList, AlbumDetail

app_name = 'album'
urlpatterns = [
    path('', AlbumList.as_view(), name='list'),
    path('<slug:slug>', AlbumDetail.as_view(), name='detail')
]

Music/urls.py
from django.urls import path
from .views import (
    MusicList,
    MusicDetail,
    like_music,
    add_to_playlist,
    del_from_favorite,
    del_from_playlist
)

app_name = 'music'
urlpatterns = [
    path('', MusicList.as_view(), name='list'),
    path('<slug:music_slug>', MusicDetail.as_view(), name='detail'),
    path('like/check/', like_music, name='like'),
    path('save/check/', add_to_playlist, name='save'),
    path('del-favorite/', del_from_favorite, name='del_favorite'),
    path('del-playlist/', del_from_playlist, name='del_playlist'),
]

Singer/urls.py
from django.urls import path
from .views import SingerList, SingerDetail

app_name = 'singer'
urlpatterns = [
    path('', SingerList.as_view(), name='list'),
    path('<slug:slug>', SingerDetail.as_view(), name='detail')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Music.views import home


urlpatterns = [
    path('', home, name='homepage'),
    path('musics/', include('Music.urls')),
    path('singers/', include('Singer.urls')),
    path('albums/', include('Album.urls')),
    path('account/', include('Account.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/home-page/albums-small-list.html
<section class="py-4">
    <div class="container">
        <h2 class="mt-0 text-center h2-color">Albums</h2>
        <hr style="height: 5px; ">
        <div class="row g-4 fixWidth">
            {% for album in albums %}
                <div class="col-lg-2 col-md-4 col-sm-6">
                    <a href="{% url 'album:detail' album.slug %}" class="card-link">
                        <div class="card--section">
                            <img class="card-image" src="{{ album.image.url }}" alt="">
                            <div class="card--detail">
                                <h3>{{ album.name|truncatewords:3 }}</h3>
                            </div>
                            <div class="card--footer">
                                <span>{{ album.musics.count }}</span>
                                <span>pop</span>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
            <div class="col-lg-2 col-md-4 col-sm-6 view-more">
                <a href="{% url 'album:list' %}">
                    <div>
                        <p>View More ...</p>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>

templates/home-page/home-most-rated-musics.html
 <div class="col-lg-4 ps-0 overflow-auto clear-most-viewed shadow scroll" style="height: 600px;">
    <h4 style="text-align: center; color: #e32d69;margin: 1px auto 0">Most Rated</h4>
    <hr style="height: 2px">
    {% for item in most_rated %}
        <a href="{% url 'music:detail' item.slug %}" style="text-decoration: none">
            <div class="item-x shadow">
                <img src="{{ item.image.url }}" alt="{{ item.name }}">
                <div class="description">
                    <p>{{ item.name }}</p>
                    <p>{{ item.singer }}</p>
                </div>
            </div>
        </a>
    {% endfor %}
</div>

templates/home-page/home-slideShow.html
{% load static %}
<div class="col-lg-8 slideImageContainerFix" style="height: 670px">
     <div class="text-center p-3 pt-0">
         <div class="slideshow">
             <div class="slides ">
                 <div class="slide active">
                     <img src="{% static 'Music/images/concert1.jfif' %}" alt="concert" class="slideImageFix">
                 </div>
                 <div class="slide">
                     <img src="{% static 'Music/images/concert2.jpg' %}" alt="concert" class="slideImageFix">
                 </div>
                 <div class="slide">
                     <img src="{% static 'Music/images/concert3.jfif' %}" alt="concert" class="slideImageFix">
                 </div>
             </div>
             <div class="points">
                 <span class="active"></span>
                 <span></span>'
                 <span></span>
             </div>
         </div>
     </div>
 </div>

templates/home-page/home.html
{% extends 'Music/base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static '../../static/Music/css/Home-style.css' %}">
    <title>Mah Music</title>
    <!-- Stylesheets -->
    <link rel="stylesheet" href="{% static '../../static/Music/carousel_assets/css/docs.theme.min.css' %}">
    <!-- Owl Stylesheets -->
    <link rel="stylesheet" href="{% static '../../static/Music/carousel_assets/owlcarousel/assets/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static '../../static/Music/carousel_assets/owlcarousel/assets/owl.theme.default.min.css' %}">
    <!-- javascript -->
    <script src="{% static '../../static/Music/carousel_assets/vendors/jquery.min.js' %}"></script>
    <script src="{% static '../../static/Music/carousel_assets/owlcarousel/owl.carousel.js' %}"></script>
{% endblock %}

{% block slide %}
    <div class="container-fluid" style="padding-top:20px ;">
        <div class="row justify-content-center align-items-start">
            {% include 'home-page/home-most-rated-musics.html' with most_rated=most_rated%}
            {% include 'home-page/home-slideShow.html' %}
        </div>
    </div>

{% endblock %}

{% block main %}
    {% include 'home-page/music-small-list.html' with new_musics=new_songs %}
{% endblock %}


{% block Singers %}
    {% include 'home-page/singers-carousel.html' with singers=singers%}
{% endblock %}


{% block Albums %}
    {% include 'home-page/albums-small-list.html' with albums=albums %}
{% endblock %}

{% block scripts %}
    <script src="{% static 'Music/js/slideShow.js' %}"></script>

    <!-- carousel Scripts -->
    <script>
      $(document).ready(function() {
        let owl = $('.owl-carousel');
        owl.owlCarousel({
          items: 4,
          loop: true,
          margin: 10,
          autoplay: true,
          autoplayTimeout: 3000,
          autoplayHoverPause: true
        });
      })
    </script>
    <!-- vendors -->
    <script src="{% static 'Music/carousel_assets/vendors/highlight.js' %}"></script>
    <script src="{% static 'Music/carousel_assets/js/app.js' %}"></script>
{% endblock %}

templates/home-page/music-small-list.html
<section class="py-4">
    <div class="container">
        <h2 class="mt-0 text-center h2-color">New songs</h2>
        <hr style="height: 5px; ">
        <div class="row g-4 fixWidth">
            {% for music in new_musics %}
                <div class="col-lg-2 col-md-4 col-sm-6 my-2">
                    <a href="{% url 'music:detail' music.slug %}" class="card-link">
                        <div class="card--section">
                            <img class="card-image" src="{{ music.image.url }}" alt="">
                            <div class="card--detail">
                                <h3>{{ music.name|truncatewords:3 }}</h3>
                            </div>
                            <div class="card--footer">
                                <span>{{ music.get_views_count }}</span>
                                <span>pop</span>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
            <div class="col-lg-2 col-md-4 col-sm-6 view-more my-2">
                    <a href="{% url 'music:list' %}">
                        <div>
                            <p>View More ...</p>
                        </div>
                    </a>
                </div>
        </div>
    </div>
</section>

templates/home-page/navbar.html
<!-- header -->
<header class="shadow sticky-top">
        <!--  navbar  -->
    <div class="sticky-top p-2 shadow"  style="border-bottom:1px solid yellow " >
        <nav class="navbar navbar-expand-lg navbar-light  container" >
                <div class="container-fluid">
                    <a class="navbar-brand fs-4 " href="#">Web Design</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"  data-bs-target="#navbarColor03"aria-controls="navbarColor03" aria-expanded="false"     aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse " id="navbarColor03">
                        <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'homepage' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Features</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Pricing</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">About</a>
                            </li>
                            {% if request.user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'account:profile' %}">Profile</a>
                                </li>
                            {% endif %}
                        </ul>
                        <div class="d-flex justify-content-lg-between justify-content-start">
                            <i class="fa fa-user-plus fs-3" style="color: rgb(79, 218, 171);"></i>
                            {% if not user.is_authenticated %}
                                <a href="{% url 'account:login' %}" class="mx-2 text-decoration-none">Sign In</a>
                                <a href="{% url 'account:register' %}" class="ms-2 text-decoration-none">Sign Up</a>
                            {% endif %}
                            {% if  user.is_authenticated %}
                                <a href="{% url 'account:logout' %}" class="ms-2 text-decoration-none">Sign Out</a>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </nav>
    </div>
</header>

templates/home-page/singers-carousel.html
<section class="py-4" id="demos">
    <div class="container">
        <h2 class="mt-0 text-center h2-color">Singers</h2>
        <hr style="height: 5px; ">
        <div class="row">
            <div class="large-12 columns">
                <div class="owl-carousel owl-theme">
                    {% for singer in singers %}
                        <a href="{% url 'singer:detail' singer.slug %}">
                            <div class="item">
                                <div class="t-box">
                                    <img src="{{ singer.image.url }}" alt="{{ singer.name }}" class="owl-carousel-image" style="height: auto">
                                    <p class="text-center">{{ singer.name }}</p>
                                </div>
                            </div>
                        </a>
                    {% endfor %}
                    <a href="{% url 'singer:list' %}">
                        <div class="item t-box" style="background: #141414 linear-gradient(to bottom,#2c2c2c,#141414);border-radius: 6px;box-shadow: 4px 4px rgb(165, 220, 17);height: 246px !important;">
                            <div>
                                <p class="text-center">All Singers..</p>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>